const Questions = {
  Cricket: [
    // Easy
    {
      difficulty: "Easy",
      ques: "Who is known as the 'Little Master'?",
      opt1: "Sachin Tendulkar",
      opt2: "Rahul Dravid",
      opt3: "Virat Kohli",
      opt4: "Brian Lara",
      corr: "Sachin Tendulkar",
    },
    {
      difficulty: "Easy",
      ques: "Which country won the first-ever ICC Cricket World Cup?",
      opt1: "India",
      opt2: "Pakistan",
      opt3: "West Indies",
      opt4: "Australia",
      corr: "West Indies",
    },
    {
      difficulty: "Easy",
      ques: "Who holds the record for the highest individual score in Test cricket?",
      opt1: "Brian Lara",
      opt2: "Sachin Tendulkar",
      opt3: "Virender Sehwag",
      opt4: "Don Bradman",
      corr: "Brian Lara",
    },
    {
      difficulty: "Easy",
      ques: "Who is the leading run-scorer in T20 International cricket?",
      opt1: "Virat Kohli",
      opt2: "Rohit Sharma",
      opt3: "David Warner",
      opt4: "Chris Gayle",
      corr: "Virat Kohli",
    },
    {
      difficulty: "Easy",
      ques: "Which bowler has taken the most wickets in ODI cricket?",
      opt1: "Wasim Akram",
      opt2: "Glenn McGrath",
      opt3: "Muttiah Muralitharan",
      opt4: "Shane Warne",
      corr: "Muttiah Muralitharan",
    },
    {
      difficulty: "Easy",
      ques: "Who is the only player to have scored a double century in ODI cricket?",
      opt1: "Rohit Sharma",
      opt2: "Sachin Tendulkar",
      opt3: "Martin Guptill",
      opt4: "Virender Sehwag",
      corr: "Sachin Tendulkar",
    },
    {
      difficulty: "Easy",
      ques: "Who is the fastest cricketer to score 10,000 runs in Test cricket?",
      opt1: "Sachin Tendulkar",
      opt2: "Virat Kohli",
      opt3: "Brian Lara",
      opt4: "Ricky Ponting",
      corr: "Sachin Tendulkar",
    },
    {
      difficulty: "Easy",
      ques: "Which player has the highest individual score in a T20 International match?",
      opt1: "Aaron Finch",
      opt2: "Chris Gayle",
      opt3: "Rohit Sharma",
      opt4: "Colin Munro",
      corr: "Aaron Finch",
    },
    {
      difficulty: "Easy",
      ques: "Who was the first bowler to take a hat-trick in an ICC Cricket World Cup match?",
      opt1: "Chetan Sharma",
      opt2: "Wasim Akram",
      opt3: "Lasith Malinga",
      opt4: "Saqlain Mushtaq",
      corr: "Chetan Sharma",
    },
    {
      difficulty: "Easy",
      ques: "Who won the ICC Cricket World Cup in 2011?",
      opt1: "India",
      opt2: "Sri Lanka",
      opt3: "Australia",
      opt4: "England",
      corr: "India",
    },

    // Medium
    {
      difficulty: "Medium",
      ques: "Who is the only player to score a century in all three formats of international cricket?",
      opt1: "Suresh Raina",
      opt2: "Rohit Sharma",
      opt3: "Virat Kohli",
      opt4: "Chris Gayle",
      corr: "Rohit Sharma",
    },
    {
      difficulty: "Medium",
      ques: "Who was the first player to score a triple century in Test cricket?",
      opt1: "Sir Don Bradman",
      opt2: "Brian Lara",
      opt3: "Virender Sehwag",
      opt4: "Sachin Tendulkar",
      corr: "Sir Don Bradman",
    },
    {
      difficulty: "Medium",
      ques: "Who has the highest individual score in a One Day International match?",
      opt1: "Rohit Sharma",
      opt2: "Martin Guptill",
      opt3: "Virender Sehwag",
      opt4: "Chris Gayle",
      corr: "Rohit Sharma",
    },
    {
      difficulty: "Medium",
      ques: "Which cricketer has the most dismissals as a wicketkeeper in ODI cricket?",
      opt1: "Adam Gilchrist",
      opt2: "Kumar Sangakkara",
      opt3: "MS Dhoni",
      opt4: "Mark Boucher",
      corr: "MS Dhoni",
    },
    {
      difficulty: "Medium",
      ques: "Who holds the record for the fastest century in Test cricket?",
      opt1: "Virender Sehwag",
      opt2: "Chris Gayle",
      opt3: "Brendon McCullum",
      opt4: "David Warner",
      corr: "Brendon McCullum",
    },
    {
      difficulty: "Medium",
      ques: "Who was the first cricketer to score 10,000 runs in Test cricket?",
      opt1: "Sachin Tendulkar",
      opt2: "Sunil Gavaskar",
      opt3: "Brian Lara",
      opt4: "Ricky Ponting",
      corr: "Sunil Gavaskar",
    },
    {
      difficulty: "Medium",
      ques: "Who was the first cricketer to score 200 runs in a One Day International match?",
      opt1: "Sachin Tendulkar",
      opt2: "Virender Sehwag",
      opt3: "Rohit Sharma",
      opt4: "Martin Guptill",
      corr: "Sachin Tendulkar",
    },
    {
      difficulty: "Medium",
      ques: "Who has the highest individual score in T20 International cricket?",
      opt1: "Aaron Finch",
      opt2: "Glenn Maxwell",
      opt3: "Rohit Sharma",
      opt4: "Chris Gayle",
      corr: "Aaron Finch",
    },
    {
      difficulty: "Medium",
      ques: "Who was the first cricketer to take 500 Test wickets?",
      opt1: "Anil Kumble",
      opt2: "Muttiah Muralitharan",
      opt3: "Shane Warne",
      opt4: "Glenn McGrath",
      corr: "Shane Warne",
    },
    {
      difficulty: "Medium",
      ques: "Who was the first cricketer to score a century in a T20 International match?",
      opt1: "Chris Gayle",
      opt2: "Brendon McCullum",
      opt3: "Yuvraj Singh",
      opt4: "Rohit Sharma",
      corr: "Chris Gayle",
    },

    // Hard
    {
      difficulty: "Hard",
      ques: "Who is the youngest player to captain a Test cricket team?",
      opt1: "Sachin Tendulkar",
      opt2: "Graeme Smith",
      opt3: "Imran Khan",
      opt4: "Nasser Hussain",
      corr: "Graeme Smith",
    },
    {
      difficulty: "Hard",
      ques: "Who was the first bowler to take all 10 wickets in a Test innings?",
      opt1: "Jim Laker",
      opt2: "Anil Kumble",
      opt3: "Muttiah Muralitharan",
      opt4: "Sydney Barnes",
      corr: "Jim Laker",
    },
    {
      difficulty: "Hard",
      ques: "Who was the first cricketer to score a century in each innings of a Test match?",
      opt1: "Sir Donald Bradman",
      opt2: "Sunil Gavaskar",
      opt3: "Ricky Ponting",
      opt4: "Steve Waugh",
      corr: "Steve Waugh",
    },
    {
      difficulty: "Hard",
      ques: "Who has the best bowling figures in a Test innings?",
      opt1: "Jim Laker",
      opt2: "Anil Kumble",
      opt3: "Muttiah Muralitharan",
      opt4: "Shane Warne",
      corr: "Jim Laker",
    },
    {
      difficulty: "Hard",
      ques: "Who was the first cricketer to score a triple century in Test cricket?",
      opt1: "Sir Donald Bradman",
      opt2: "Virender Sehwag",
      opt3: "Brian Lara",
      opt4: "Chris Gayle",
      corr: "Sir Donald Bradman",
    },
    {
      difficulty: "Hard",
      ques: "Who holds the record for the most runs scored in a single over in a Test match?",
      opt1: "Brian Lara",
      opt2: "Yuvraj Singh",
      opt3: "Herschelle Gibbs",
      opt4: "AB de Villiers",
      corr: "Brian Lara",
    },
    {
      difficulty: "Hard",
      ques: "Who was the first cricketer to score 300 runs in a One Day International match?",
      opt1: "Virender Sehwag",
      opt2: "Rohit Sharma",
      opt3: "Chris Gayle",
      opt4: "Martin Guptill",
      corr: "Virender Sehwag",
    },
    {
      difficulty: "Hard",
      ques: "Who holds the record for the most catches in Test cricket?",
      opt1: "Rahul Dravid",
      opt2: "Jacques Kallis",
      opt3: "Mark Waugh",
      opt4: "Steve Waugh",
      corr: "Rahul Dravid",
    },
    {
      difficulty: "Hard",
      ques: "Who was the first cricketer to take 800 Test wickets?",
      opt1: "Muttiah Muralitharan",
      opt2: "Shane Warne",
      opt3: "Anil Kumble",
      opt4: "Glenn McGrath",
      corr: "Muttiah Muralitharan",
    },
    {
      difficulty: "Hard",
      ques: "Who has the most centuries in Test cricket?",
      opt1: "Ricky Ponting",
      opt2: "Sachin Tendulkar",
      opt3: "Virat Kohli",
      opt4: "Steve Smith",
      corr: "Sachin Tendulkar",
    },
  ],

  Physics: [
    // Easy
    {
      difficulty: "Easy",
      ques: "What is the SI unit of speed?",
      opt1: "m/s",
      opt2: "km/s",
      opt3: "m/h",
      opt4: "km/h",
      corr: "m/s",
    },
    {
      difficulty: "Easy",
      ques: "What is the SI unit of force?",
      opt1: "Newton",
      opt2: "Joule",
      opt3: "Watt",
      opt4: "Pascal",
      corr: "Newton",
    },
    {
      difficulty: "Easy",
      ques: "What is the SI unit of energy?",
      opt1: "Joule",
      opt2: "Newton",
      opt3: "Watt",
      opt4: "Pascal",
      corr: "Joule",
    },
    {
      difficulty: "Easy",
      ques: "What is the SI unit of power?",
      opt1: "Watt",
      opt2: "Joule",
      opt3: "Newton",
      opt4: "Pascal",
      corr: "Watt",
    },
    {
      difficulty: "Easy",
      ques: "What is the acceleration due to gravity on Earth?",
      opt1: "9.8 m/s²",
      opt2: "10 m/s²",
      opt3: "8.2 m/s²",
      opt4: "11 m/s²",
      corr: "9.8 m/s²",
    },
    {
      difficulty: "Easy",
      ques: "What is the SI unit of electric current?",
      opt1: "Ampere",
      opt2: "Volt",
      opt3: "Ohm",
      opt4: "Watt",
      corr: "Ampere",
    },
    {
      difficulty: "Easy",
      ques: "What is the SI unit of electric charge?",
      opt1: "Coulomb",
      opt2: "Ampere",
      opt3: "Volt",
      opt4: "Ohm",
      corr: "Coulomb",
    },
    {
      difficulty: "Easy",
      ques: "What is the SI unit of resistance?",
      opt1: "Ohm",
      opt2: "Ampere",
      opt3: "Volt",
      opt4: "Watt",
      corr: "Ohm",
    },
    {
      difficulty: "Easy",
      ques: "What is the SI unit of voltage?",
      opt1: "Volt",
      opt2: "Ampere",
      opt3: "Ohm",
      opt4: "Watt",
      corr: "Volt",
    },
    {
      difficulty: "Easy",
      ques: "What is the SI unit of frequency?",
      opt1: "Hertz",
      opt2: "Joule",
      opt3: "Pascal",
      opt4: "Watt",
      corr: "Hertz",
    },

    // Medium
    {
      difficulty: "Medium",
      ques: "What is the SI unit of capacitance?",
      opt1: "Farad",
      opt2: "Ohm",
      opt3: "Hertz",
      opt4: "Watt",
      corr: "Farad",
    },
    {
      difficulty: "Medium",
      ques: "What is the SI unit of magnetic field?",
      opt1: "Tesla",
      opt2: "Ohm",
      opt3: "Pascal",
      opt4: "Farad",
      corr: "Tesla",
    },
    {
      difficulty: "Medium",
      ques: "What is the SI unit of magnetic flux?",
      opt1: "Weber",
      opt2: "Tesla",
      opt3: "Joule",
      opt4: "Pascal",
      corr: "Weber",
    },
    {
      difficulty: "Medium",
      ques: "What is the SI unit of temperature?",
      opt1: "Kelvin",
      opt2: "Celsius",
      opt3: "Fahrenheit",
      opt4: "Rankine",
      corr: "Kelvin",
    },
    {
      difficulty: "Medium",
      ques: "What is the SI unit of luminous intensity?",
      opt1: "Candela",
      opt2: "Lumen",
      opt3: "Lux",
      opt4: "Tesla",
      corr: "Candela",
    },
    {
      difficulty: "Medium",
      ques: "What is the SI unit of sound intensity?",
      opt1: "Decibel",
      opt2: "Hertz",
      opt3: "Pascal",
      opt4: "Watt",
      corr: "Decibel",
    },
    {
      difficulty: "Medium",
      ques: "What is the SI unit of momentum?",
      opt1: "Kilogram meter per second",
      opt2: "Meter per second squared",
      opt3: "Newton meter",
      opt4: "Newton meter per second",
      corr: "Kilogram meter per second",
    },
    {
      difficulty: "Medium",
      ques: "What is the SI unit of electric potential?",
      opt1: "Volt",
      opt2: "Watt",
      opt3: "Ohm",
      opt4: "Ampere",
      corr: "Volt",
    },
    {
      difficulty: "Medium",
      ques: "What is the SI unit of magnetic flux density?",
      opt1: "Tesla",
      opt2: "Weber",
      opt3: "Ohm",
      opt4: "Pascal",
      corr: "Tesla",
    },
    {
      difficulty: "Medium",
      ques: "What is the SI unit of work?",
      opt1: "Joule",
      opt2: "Newton",
      opt3: "Watt",
      opt4: "Pascal",
      corr: "Joule",
    },

    // Hard
    {
      difficulty: "Hard",
      ques: "What is the unit of resistance in the International System of Units (SI)?",
      opt1: "Ohm",
      opt2: "Ampere",
      opt3: "Volt",
      opt4: "Coulomb",
      corr: "Ohm",
    },
    {
      difficulty: "Hard",
      ques: "What is the SI unit of inductance?",
      opt1: "Henry",
      opt2: "Pascal",
      opt3: "Coulomb",
      opt4: "Watt",
      corr: "Henry",
    },
    {
      difficulty: "Hard",
      ques: "What is the SI unit of electric conductance?",
      opt1: "Siemens",
      opt2: "Henry",
      opt3: "Tesla",
      opt4: "Watt",
      corr: "Siemens",
    },
    {
      difficulty: "Hard",
      ques: "What is the SI unit of magnetic flux density?",
      opt1: "Tesla",
      opt2: "Henry",
      opt3: "Weber",
      opt4: "Ampere",
      corr: "Tesla",
    },
    {
      difficulty: "Hard",
      ques: "What is the SI unit of luminance?",
      opt1: "Candela per square meter",
      opt2: "Lumen",
      opt3: "Candela",
      opt4: "Luxe",
      corr: "Candela per square meter",
    },
    {
      difficulty: "Hard",
      ques: "What is the SI unit of capacitance?",
      opt1: "Farad",
      opt2: "Henry",
      opt3: "Tesla",
      opt4: "Weber",
      corr: "Farad",
    },
    {
      difficulty: "Hard",
      ques: "What is the SI unit of magnetic susceptibility?",
      opt1: "Dimensionless",
      opt2: "Henry",
      opt3: "Weber",
      opt4: "Tesla",
      corr: "Dimensionless",
    },
    {
      difficulty: "Hard",
      ques: "What is the SI unit of refractive index?",
      opt1: "Dimensionless",
      opt2: "Meter per second",
      opt3: "Coulomb",
      opt4: "Newton",
      corr: "Dimensionless",
    },
    {
      difficulty: "Hard",
      ques: "What is the SI unit of magnetic permeability?",
      opt1: "Henry per meter",
      opt2: "Ohm meter",
      opt3: "Tesla meter",
      opt4: "Newton meter",
      corr: "Henry per meter",
    },
    {
      difficulty: "Hard",
      ques: "What is the SI unit of specific heat capacity?",
      opt1: "Joule per kilogram per kelvin",
      opt2: "Newton per meter squared",
      opt3: "Pascal second",
      opt4: "Henry",
      corr: "Joule per kilogram per kelvin",
    },
  ],

  Chemistry: [
    // Easy
    {
      difficulty: "Easy",
      ques: "What is the chemical symbol for water?",
      opt1: "H2O",
      opt2: "CO2",
      opt3: "NaCl",
      opt4: "O2",
      corr: "H2O",
    },
    {
      difficulty: "Easy",
      ques: "What is the chemical symbol for oxygen?",
      opt1: "O",
      opt2: "O2",
      opt3: "H2O",
      opt4: "CO2",
      corr: "O2",
    },
    {
      difficulty: "Easy",
      ques: "What is the pH of a neutral solution?",
      opt1: "7",
      opt2: "8",
      opt3: "6",
      opt4: "5",
      corr: "7",
    },
    {
      difficulty: "Easy",
      ques: "What is the chemical symbol for carbon dioxide?",
      opt1: "CO",
      opt2: "O2",
      opt3: "CO2",
      opt4: "C2H5OH",
      corr: "CO2",
    },
    {
      difficulty: "Easy",
      ques: "What is the chemical formula for table salt?",
      opt1: "NaCl",
      opt2: "KCl",
      opt3: "HCl",
      opt4: "NaOH",
      corr: "NaCl",
    },
    {
      difficulty: "Easy",
      ques: "What gas do plants use in photosynthesis?",
      opt1: "Carbon Dioxide",
      opt2: "Oxygen",
      opt3: "Nitrogen",
      opt4: "Hydrogen",
      corr: "Carbon Dioxide",
    },
    {
      difficulty: "Easy",
      ques: "What is the chemical symbol for gold?",
      opt1: "Au",
      opt2: "Ag",
      opt3: "Pt",
      opt4: "Fe",
      corr: "Au",
    },
    {
      difficulty: "Easy",
      ques: "What is the chemical formula for methane?",
      opt1: "CH4",
      opt2: "CO2",
      opt3: "H2O",
      opt4: "NH3",
      corr: "CH4",
    },
    {
      difficulty: "Easy",
      ques: "What is the chemical symbol for iron?",
      opt1: "Fe",
      opt2: "Au",
      opt3: "Ag",
      opt4: "Pb",
      corr: "Fe",
    },
    {
      difficulty: "Easy",
      ques: "What is the chemical formula for sulfuric acid?",
      opt1: "H2SO4",
      opt2: "HCl",
      opt3: "NaOH",
      opt4: "NH3",
      corr: "H2SO4",
    },

    // Medium
    {
      difficulty: "Medium",
      ques: "What is the chemical formula for ammonia?",
      opt1: "NH3",
      opt2: "NO2",
      opt3: "H2O",
      opt4: "CO2",
      corr: "NH3",
    },
    {
      difficulty: "Medium",
      ques: "What is the chemical formula for hydrochloric acid?",
      opt1: "HCl",
      opt2: "H2SO4",
      opt3: "NaOH",
      opt4: "NH3",
      corr: "HCl",
    },
    {
      difficulty: "Medium",
      ques: "What is the chemical formula for nitric acid?",
      opt1: "HNO3",
      opt2: "HCl",
      opt3: "NaOH",
      opt4: "NH3",
      corr: "HNO3",
    },
    {
      difficulty: "Medium",
      ques: "What is the chemical formula for sulfur dioxide?",
      opt1: "SO2",
      opt2: "SO3",
      opt3: "H2SO4",
      opt4: "Na2SO4",
      corr: "SO2",
    },
    {
      difficulty: "Medium",
      ques: "What is the chemical formula for sodium hydroxide?",
      opt1: "NaOH",
      opt2: "NaCl",
      opt3: "Na2CO3",
      opt4: "NaHCO3",
      corr: "NaOH",
    },
    {
      difficulty: "Medium",
      ques: "What gas is produced when vinegar and baking soda are mixed?",
      opt1: "Carbon Dioxide",
      opt2: "Oxygen",
      opt3: "Nitrogen",
      opt4: "Hydrogen",
      corr: "Carbon Dioxide",
    },
    {
      difficulty: "Medium",
      ques: "What is the chemical formula for calcium carbonate?",
      opt1: "CaCO3",
      opt2: "CaCl2",
      opt3: "CaSO4",
      opt4: "Ca(OH)2",
      corr: "CaCO3",
    },
    {
      difficulty: "Medium",
      ques: "What is the chemical formula for potassium nitrate?",
      opt1: "KNO3",
      opt2: "KCl",
      opt3: "KHCO3",
      opt4: "KOH",
      corr: "KNO3",
    },
    {
      difficulty: "Medium",
      ques: "What is the chemical formula for carbonic acid?",
      opt1: "H2CO3",
      opt2: "HCl",
      opt3: "HNO3",
      opt4: "H2SO4",
      corr: "H2CO3",
    },
    {
      difficulty: "Medium",
      ques: "What gas do humans exhale when breathing?",
      opt1: "Carbon Dioxide",
      opt2: "Oxygen",
      opt3: "Nitrogen",
      opt4: "Hydrogen",
      corr: "Carbon Dioxide",
    },

    // Hard
    {
      difficulty: "Hard",
      ques: "What is the chemical formula for hydrofluoric acid?",
      opt1: "HF",
      opt2: "H2SO4",
      opt3: "HNO3",
      opt4: "HCl",
      corr: "HF",
    },
    {
      difficulty: "Hard",
      ques: "What is the chemical formula for phosphoric acid?",
      opt1: "H3PO4",
      opt2: "H2SO4",
      opt3: "HCl",
      opt4: "HF",
      corr: "H3PO4",
    },
    {
      difficulty: "Hard",
      ques: "What is the chemical formula for acetic acid?",
      opt1: "CH3COOH",
      opt2: "H2SO4",
      opt3: "HNO3",
      opt4: "HCl",
      corr: "CH3COOH",
    },
    {
      difficulty: "Hard",
      ques: "What is the chemical formula for sulfuric acid?",
      opt1: "H2SO4",
      opt2: "HCl",
      opt3: "HNO3",
      opt4: "HF",
      corr: "H2SO4",
    },
    {
      difficulty: "Hard",
      ques: "What is the chemical formula for nitrous oxide?",
      opt1: "N2O",
      opt2: "NO2",
      opt3: "NO",
      opt4: "N2",
      corr: "N2O",
    },
    {
      difficulty: "Hard",
      ques: "What is the chemical formula for hydrobromic acid?",
      opt1: "HBr",
      opt2: "H2SO4",
      opt3: "HNO3",
      opt4: "HCl",
      corr: "HBr",
    },
    {
      difficulty: "Hard",
      ques: "What is the chemical formula for potassium permanganate?",
      opt1: "KMnO4",
      opt2: "K2Cr2O7",
      opt3: "KNO3",
      opt4: "KClO3",
      corr: "KMnO4",
    },
    {
      difficulty: "Hard",
      ques: "What is the chemical formula for carbon monoxide?",
      opt1: "CO",
      opt2: "CO2",
      opt3: "CH4",
      opt4: "C2H6",
      corr: "CO",
    },
    {
      difficulty: "Hard",
      ques: "What is the chemical formula for ammonium nitrate?",
      opt1: "NH4NO3",
      opt2: "NH3",
      opt3: "NO3",
      opt4: "NH4",
      corr: "NH4NO3",
    },
    {
      difficulty: "Hard",
      ques: "What is the chemical formula for sodium bicarbonate?",
      opt1: "NaHCO3",
      opt2: "Na2CO3",
      opt3: "NaCl",
      opt4: "NaOH",
      corr: "NaHCO3",
    },
  ],
};

export default Questions;
